- name: Copy configuration for 5GHz AP
  vars:
    ___anchors___:
      register: &register
        register: self_result
        changed_when: run_handlers or (self_result.changed and reconfigure_now)
  template:
    src: hostapd.conf.j2
    dest: "/etc/hostapd/{{ ap5_interface_name }}.conf"
    mode: "600"
    owner: root
    group: root
  <<: *register
  notify: Restart hostapd@{{ ap5_interface_name }}

- name: Copy netplan configuration files for 5GHz AP
  template:
    src: netplan.yaml.j2
    dest: "/etc/netplan/{{ global_netplan_slave_order }}-{{ ap5_interface_name }}.yaml"
    mode: "644"
    owner: root
    group: root
  <<: *register
  notify: "netplan : Apply netplan configuration"

- name: Enable hostapd@{{ ap5_interface_name }}
  service:
    name: hostapd@{{ ap5_interface_name }}
    enabled: yes

