- name: Forbid system sleep, hibernate, etc...
  vars:
    ___anchors___:
      register: &register
        register: self_result
        changed_when: run_handlers or (self_result.changed and reconfigure_now)
  ini_file:
    path: /etc/systemd/sleep.conf
    create: no
    no_extra_spaces: yes
    section: Sleep
    option: "{{ item.option }}"
    state: present
    value: "{{ item.value }}"
  loop:
    - option: AllowSuspend
      value: "no"
    - option: AllowHibernation
      value: "no"
    - option: AllowSuspendThenHibernate
      value: "no"
    - option: AllowHybridSleep
      value: "no"
  <<: *register
  notify: Reload systemd

- name: Install service to poweroff the TTY
  template:
    src: console-power.service.j2
    dest: /etc/systemd/system/console-power.service
    owner: root
    group: root
    mode: "644"
  <<: *register
  notify: Restart console-power

- name: Enable console-power
  systemd:
    name: console-power
    enabled: yes
    daemon_reload: yes
