- name: Prepare the router
  hosts: all
  ignore_errors: "{{ keep_going }}"
  become: yes
  pre_tasks:
    - name: Update package lists
      apt:
        update_cache: yes
      changed_when: no
  roles:
    - role: lan-bridge/defaults
    - role: ap5
      ap5_bridge: "{{ lan_bridge_interface_name }}"
      when: enable_ap5
    - role: ap24
      ap24_bridge: "{{ lan_bridge_interface_name }}"
      when: enable_ap24
    - role: wired-lan
      when: enable_wired_lan
    - role: lan-bridge
      # AP interfaces are added to the bridge by hostapd itself.
      # No need to do that here.
      lan_bridge_slaves: >
        {%- set l = [] -%}
        {%- if enable_wired_lan -%}
          {%- set l = l + wired_lan_interfaces | map(attribute='name') -%}
        {%- endif -%}
        {{- l -}}
    - role: wan
    - role: routing
      routing_lan_nic: "{{ lan_bridge_interface_name }}"
      routing_wan_nic: "{{ wan_ppp_interface_name }}"
    - role: powersave
      when: enable_powersave
    - role: rtl8812bu
      rtl8812bu_vht_enable: "{{ ap5_vht_enable }}"
      when: enable_rtl8812bu

# vi: set sts=-1 et sw=2 :
